### ISSUE TITLE
xml.parsers.expat.ExpatError: duplicate attribute

### ISSUE THREAD

**Issue by mikusjelly** [mikusjelly/apkutils#4]
```
$ python -m apkutils.apk -m 312792279738e239c01d7a8636ca83bf.apk
Traceback (most recent call last):
  File "...\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\lib\site-packages\apkutils\apk.py", line 375, in <module>
    main(_args)
  File "...\lib\site-packages\apkutils\apk.py", line 354, in main
    print(json.dumps(apk.get_manifest(), indent=1))
  File "...\lib\site-packages\apkutils\apk.py", line 86, in get_manifest
    self._init_manifest()
  File "...\lib\site-packages\apkutils\apk.py", line 106, in _init_manifest
    raise e
  File "...\lib\site-packages\apkutils\apk.py", line 104, in _init_manifest
    raise e
  File "...\lib\site-packages\apkutils\apk.py", line 102, in _init_manifest
    raise e
  File "...\lib\site-packages\apkutils\apk.py", line 100, in _init_manifest
    axml.get_xml())['manifest']
  File "...\lib\site-packages\xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: duplicate attribute: line 290, column 0
```

**Comment by mikusjelly** [comment]
```
  <receiver
            android:label="...."
            android:label="..."
```
同一个标签存在两个名字一样的属性，xmltodict 转为字典的时候，由于key一样，导致失败。
