### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by mikusjelly** [mikusjelly/apkutils#6]
```
0c856bbccab2a7fc7b477df68f3289d0
41b94ec1202fe6e06726362052374b6d

$ python -m apkutils.apk -s 41b94ec1202fe6e06726362052374b6d.apk
Warning, unexpected header size!
Warning, unexpected endianess tag!
Traceback (most recent call last):
  File "...\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\lib\site-packages\apkutils\apk.py", line 375, in <module>
    main(_args)
  File "...\lib\site-packages\apkutils\apk.py", line 357, in main
    for item in apk.get_strings():
  File "...\lib\site-packages\apkutils\apk.py", line 41, in get_strings
    self._init_strings()
  File "...\lib\site-packages\apkutils\apk.py", line 51, in _init_strings
    str_set.add(binascii.hexlify(dex_file.string(i)).decode())
  File "...\lib\site-packages\apkutils\dex\dexparser.py", line 300, in string
    stream.uleb128()  # ignore decoded length
  File "...\lib\site-packages\apkutils\dex\byteio.py", line 65, in uleb128
    return self._leb128()
  File "...\lib\site-packages\apkutils\dex\byteio.py", line 52, in _leb128
    while self.data[self.pos] >> 7:
IndexError: index out of range
```

**Comment by mikusjelly** [comment]
classes2.dex is a elf, not dex.
